# Generated by Django 4.1.7 on 2023-05-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_author_user_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
